### PR TITLE
Heart container using attributes

### PR DESCRIPTION
**Pull request by BlueAgent**
## Minecraft version & Mod Version:
Minecraft: 1.12.2
Forge: 14.23.4.2727
Cyclic: 1.12.2-1.15.16 (changes based on https://github.com/PrinceOfAmber/Cyclic/commit/d49bf8f7f07b991e5e59812340411293488ae625)
### Mods that change health:
Botania: r1.10-354
Nutrition: 1.12.2-3.4.0
ScalingHealth: 1.12-1.3.18-101
solcarrot: 1.12.2-1.3.3
### Supporting mods in test profile:
AppleCore: mc1.12.2-3.1.3
Baubles: 1.12-1.5.2
CraftTweaker2: 1.12-4.1.9
Just Enough Items: 1.12.2-4.11.0.202
SilentLib: 1.12-2.2.18-100

## Single player or Server:
Both are affected

## Describe problem (what you were doing / what happened):
Cyclic heart canisters do not stack properly with other mods that modify health.
Especially apparant with Scaling Health, it also has a feature that changes starting health similar to starting heart canisters like Cyclic.

The cause of this is using setBaseValue on the health attribute. This would conflict with mods that either change the base value or base calculations on it in an incompatible way.
In Scaling Health's case it [calculates bonus health based on getBaseValue](https://github.com/SilentChaos512/ScalingHealth/blob/0587db0053df5f822eb1f1f061bdef6587ef8334/common/net/silentchaos512/scalinghealth/utils/ModifierHandler.java#L29) to work out what its modifier should be to adjust the starting health (starting health - base health + bonus health).

### Least disruptive change (the one currently being PR'ed):
Modify the `UtilEntity.setMaxHealth` and `UtilEntity.getMaxHealth` to use an AttributeModifier instead of setBaseValue.
[Here is a video with these changes](https://youtu.be/_JkuL08YvI4)

### Change to being bonus health insted of max health:
This would involve updating Cyclic's player data store, in addition we should also make the health boost source the heart container itself so that in the future.
This change can be applied after the previous suggested change, if you make use of the same UUID but have it for the heart canisters it will replace it.
This is is not crucial if no plans for other methods to increase in the future, and might not be required if cyclic internally uses just a single attribute modifiers but collects the absolute modifier itself from the sources in the mod and they're all flat changes.

For reference the "operation" part of modifiers, I couldn't find it documented anywhere, but here's what the effect seems to be:

0 - Flat increase (+X)
1 - Additive Percentage increase (+X%)
2 - Multiplicative Percentage increase ((1+X)%)

`RESULT = (BASE + SUM(T0_i)) * (1 + SUM(T1_i) * PRODUCT(1 + T2_i)`

## Related Issues
https://github.com/PrinceOfAmber/Cyclic/issues/614 (Original Issue)
https://github.com/PrinceOfAmber/Cyclic/issues/785 (Duplicate)
https://github.com/PrinceOfAmber/Cyclic/issues/833 (Semi-related, the root cause is similar)

## Original
<details>
<summary>Click to expand</summary>
Dear PrinceOfAmber,

This is a minimal change that allows Cyclic's health modifier to be compatible with other mods that also affect health, by making use of attribute modifiers.

The downsides to this change is get/setMaxHealth being a misnomer since it'll be ignoring the health boosts from other mods, so it's really get/setBaseHealthPlusBonusCyclicHealth. In essence it's quite the bandaid fix, but also the least intrusive one.

Idealy there would be an attribute modifier for each source, so if cyclic were to add other health attribute modifiers in the future they would stack properly.

When first assessing potential changes, identified that it would be quite the intrusive change if this were to be changed from maxHealth to being bonusHealthFromHeartCanisters. It would involve making a breaking change to the Cyclic player data, which currently stores the maxHealth. This field would need to be changed, perhaps adding a "version" field to the cyclic player data would be a good way to keep track of the version of the player data, this way you could have the player data be updated by maintaining a method to update old player data in case of such breaking changes in the future.

This pull request is really opening the discussion, very interested to hear about what your thoughts on this are.

Regards,
BlueAgent
</details>

### CODE REVIEW

**Comment by BlueAgent** [comment]
Noticed a a similar issue with the Block Reach enchantment as well, it's a similar case to this one and can also be fixed by making use of AttributeModifiers.

**Comment by PrinceOfAmber** [comment]
This looks really awesome! I have used IAttributeInstance type system for mobs and entities but not for players.  

Ill grab this and test it today or tomorrow.   Looks like it should also be compatible with the command and the default config because of the util wrapper :D 
https://github.com/PrinceOfAmber/Cyclic/blob/2605b8490eff291a7fa6617dd425681b7da1f15e/src/main/java/com/lothrazar/cyclicmagic/command/CommandHearts.java#L77

https://github.com/PrinceOfAmber/Cyclic/blob/2605b8490eff291a7fa6617dd425681b7da1f15e/src/main/java/com/lothrazar/cyclicmagic/event/EventPlayerData.java#L82

**Comment by PrinceOfAmber** [comment]
Also the PR description is amazing, very thurough.  If this was a job I would hire you on the spot!

**Comment by BlueAgent** [comment]
Thanks for reviewing this PR and the nice comments.

[Here's a link to a video with some cursory manual testing.](https://youtu.be/_JkuL08YvI4)
Made use of the `sethearts` command in it which sems to work okay.

Actually, initially targeted the development branch cause it seemed to be a better match with the workflow (features are merged into develop then master), but switched it to the master branch cause I was unsure after taking a look at other PRs which targeted master.

**Comment by PrinceOfAmber** [comment]
I pretty much only PR into master when i do a release and then link to curse page, and develop is the working copy of future release

(if a PR is just a language file i usually get lazy and let it hit master first)

**Comment by PrinceOfAmber** [comment]
Also i just tested and this is backwards compatible.  Meaning, i had an old world with a character at 20 hearts, updated to this build and i still have 20 so no loss 💃

**Comment by BlueAgent** [comment]
What may happen is if someone was previously at 19 hearts, and then eats a heart after the update, it'd give them another 10 hearts, ending up at 29 hearts, but it should reset if they die or exit the end through the portal.

**Pull request merged**
