### PR TITLE
Assets optimization

### PR DESCRIPTION
**Pull request by K0-RR**
Lossless compression using the Leanify tool

### CODE REVIEW

**Comment by Lothrazar** [comment]
can you explain a bit more about this?

**Comment by Lothrazar** [comment]
can you explain a bit more about this?

For example what benefit does it do, what bug does it fix? if any?

**Comment by metalshark** [comment]
> can you explain a bit more about this?
> 
> For example what benefit does it do, what bug does it fix? if any?

This looks like they've just minified (shrunk redundant information) out of all the textures. PNGs can often have their file size reduced losslessly. It's CPU intensive to do the size reduction, but not so for reading the PNGs later on. This just reduces the file sizes without any degradation. Looking at the before/after PNG files will show them as identical but the file sizes have been reduced significantly.

**Comment by K0-RR** [comment]
Sorry for taking so long to respond. Everything @metalshark said is correct. There is no downside to this change and the only advantage is the size reduction.

**Comment by Lothrazar** [comment]
does it show any measurable difference in runtime performance? like in-game

**Comment by metalshark** [comment]
It'll load from disk imperceivably faster, but use the same amount of memory and have no difference in terms of CPU/RAM once assets have loaded. It's going to be difficult to know the difference in terms of CPU/RAM for loading, but generally, it's the case that there's no real change (some may use more, some less).

The real difference will be a smaller JAR file for people to download.

**Pull request closed without merging**
