### PR TITLE
Implement different directions as non-random (yet unpredictable) across entire code base and move random direction getter to utility class

### PR DESCRIPTION
**Pull request by metalshark**
Changed from an iterator to explicit iteration achieving the same and removing random.
Used this implementation across the entire code base.
Moved the getRandom function from the DiceTile to the utility class removing TODO.

### CODE REVIEW

**Comment by Lothrazar** [comment]
i got distracted by porting 1.18, but yeah this looks good!

**Comment by metalshark** [comment]
Have a new PR I’m testing and tidying up with huge performance increases and a
few TODOs addressed. The getCapabities wasn’t implemented correctly in a
few places and there’s no invalidateCaps. By doing those correctly and
caching adjacent capabilities (invalidating the caching using the
addListener on the LazyOptional) and also caching the EnumConnectType
instead of querying the BlockState each time (which if the chunk is flagged
dirty caused a getChunk) the system now flies along.

**Comment by metalshark** [comment]
@Lothrazar https://github.com/metalshark/Cyclic/tree/cache if you're interested in the performance increases. It's a biggie so will get all parts in and break it into smaller PRs.

**Comment by Lothrazar** [comment]
Cool! Im releasing this soon in 1.16.5 - 1.5.12 .  Let me know when new version is up, or if i  dont respond those pings go to the github app on my phone now (also on discord/twitter) .

**Pull request merged**
